#pragma once

namespace bfc {
  enum KeyCode {
    KeyCode_Unknown = -1,
    KeyCode_A,
    KeyCode_B,
    KeyCode_C,
    KeyCode_D,
    KeyCode_E,
    KeyCode_F,
    KeyCode_G,
    KeyCode_H,
    KeyCode_I,
    KeyCode_J,
    KeyCode_K,
    KeyCode_L,
    KeyCode_M,
    KeyCode_N,
    KeyCode_O,
    KeyCode_P,
    KeyCode_Q,
    KeyCode_R,
    KeyCode_S,
    KeyCode_T,
    KeyCode_U,
    KeyCode_V,
    KeyCode_W,
    KeyCode_X,
    KeyCode_Y,
    KeyCode_Z,
    KeyCode_0,
    KeyCode_1,
    KeyCode_2,
    KeyCode_3,
    KeyCode_4,
    KeyCode_5,
    KeyCode_6,
    KeyCode_7,
    KeyCode_8,
    KeyCode_9,

    KeyCode_LeftArrow,
    KeyCode_RightArrow,
    KeyCode_UpArrow,
    KeyCode_DownArrow,
    KeyCode_Enter,
    KeyCode_Backspace,
    KeyCode_Space,
    KeyCode_Comma,
    KeyCode_Period,
    KeyCode_Apostrophe,
    KeyCode_Pipe,
    KeyCode_Semicolon,
    KeyCode_Grave,
    KeyCode_Tab,
    KeyCode_CapsLock,
    KeyCode_Shift,
    KeyCode_Control,
    KeyCode_Alt,
    KeyCode_Menu,
    KeyCode_Slash,
    KeyCode_Backslash,
    KeyCode_LeftBracket,
    KeyCode_RightBracket,
    KeyCode_Minus,
    KeyCode_Equals,
    KeyCode_Insert,
    KeyCode_Delete,
    KeyCode_Home,
    KeyCode_End,
    KeyCode_PageUp,
    KeyCode_PageDown,
    KeyCode_Escape,
    KeyCode_Super,
    KeyCode_ScrollLock,
    KeyCode_NumLock,
    KeyCode_PrintScreen,
    KeyCode_Pause,

    KeyCode_F1,
    KeyCode_F2,
    KeyCode_F3,
    KeyCode_F4,
    KeyCode_F5,
    KeyCode_F6,
    KeyCode_F7,
    KeyCode_F8,
    KeyCode_F9,
    KeyCode_F10,
    KeyCode_F11,
    KeyCode_F12,

    KeyCode_Keypad0,
    KeyCode_Keypad1,
    KeyCode_Keypad2,
    KeyCode_Keypad3,
    KeyCode_Keypad4,
    KeyCode_Keypad5,
    KeyCode_Keypad6,
    KeyCode_Keypad7,
    KeyCode_Keypad8,
    KeyCode_Keypad9,
    KeyCode_KeypadDecimal,
    KeyCode_KeypadDivide,
    KeyCode_KeypadMultiply,
    KeyCode_KeypadSubtract,
    KeyCode_KeypadAdd,
    KeyCode_KeypadEnter,
    KeyCode_KeypadEqual,

    KeyCode_ModCtrl,
    KeyCode_ModShift,
    KeyCode_ModAlt,
    KeyCode_ModSuper,
    KeyCode_Count
  };

  enum MouseButton {
    MouseButton_Unknown = -1,
    MouseButton_Left,
    MouseButton_Right,
    MouseButton_Middle,
    MouseButton_Count,
    MouseButton_0 = MouseButton_Count,
    MouseButton_1,
    MouseButton_2,
    MouseButton_3,
    MouseButton_4,
    MouseButton_5,
    MouseButton_6,
    MouseButton_7,
    MouseButton_8,
    MouseButton_9,
    MouseButton_ExtendedCount,
  };
}
